'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("resort_management.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _360_F_836184489_cfMhQdClJd7SBQ6n2CSsh8UI7SnAX1gp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("360_F_836184489_cfMhQdClJd7SBQ6n2CSsh8UI7SnAX1gp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _82d0f633_ae6b_448d_b123_a2bba19b5cc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("82d0f633-ae6b-448d-b123-a2bba19b5cc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8f6dde35a588e10e3e215f9922e2bd7e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8f6dde35a588e10e3e215f9922e2bd7e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property account_box_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_box_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_downward_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_downward_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_forward_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_left_alt_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left_alt_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_upward_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_upward_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bar_chart_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar_chart_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bedroom_parent_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bedroom_parent_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancel_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cb1d0c45649cce9c6a908750f81e1cdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cb1d0c45649cce9c6a908750f81e1cdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property concierge_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("concierge_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crysttal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crysttal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property event_upcoming_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("event_upcoming_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inventory_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventory_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_book_2_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_book_2_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property person_add_70dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person_add_70dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property point_of_sale_100dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("point_of_sale_100dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property point_of_sale_200dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("point_of_sale_200dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property print_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property receipt_200dp_000000_FILL1_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("receipt_200dp_000000_FILL1_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reception() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reception", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_90dp_000000_FILL0_wght400_GRAD0_opsz48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_90dp_000000_FILL0_wght400_GRAD0_opsz48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property swimming_pool_at_a_tropical_resort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swimming-pool-at-a-tropical-resort", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
